CREATE DATABASE orderDB1
USE DATABASE orderDB1
CREATE TABLE restaurant (id INT NOT NULL,name CHAR(25) NOT NULL,address CHAR(100),phone CHAR(20),rate FLOAT,PRIMARY KEY (id))
CREATE TABLE customer(id INT NOT NULL,name CHAR(25) NOT NULL,gender CHAR(1) NOT NULL,PRIMARY KEY (id))
CREATE TABLE food(id INT NOT NULL,restaurant_id INT,name CHAR(100) NOT NULL,price FLOAT NOT NULL,PRIMARY KEY (id))
CREATE TABLE orders(id INT NOT NULL,customer_id INT NOT NULL,food_id INT NOT NULL,date1 CHAR(10),quantity INT,PRIMARY KEY (id))

